### ISSUE TITLE
Npm name 

### ISSUE THREAD

**Issue by alidcastano** [alidcastano/rogue#1]
Hey @mkay581 are you still using the `rogue` npm name? I couldn't find any repo for it but did see that you published a package under it.

If you're not using it, are you willing to give it away? I'm creating a SSR framework for React, with the tagline that it's "quick and invisible" so I'd love to use that name.

I didn't know how else to reach you, so if you see this let me know, thanks!

**Comment by mkay581** [comment]
Sure, doesn't look like its been in use and I certainly no longer have a repo for it! :+1:

**Comment by alidcastano** [comment]
awesome, if you can grant me access then that'd be great - my npm name is alidcastano

**Comment by mkay581** [comment]
done! Feel free to remove/manage it as you wish! Rogue sounds like a great idea. Feel free to reach out to me if you have any more questions :wink:

**Comment by alidcastano** [comment]
Thanks Mark, happy coding!

**Comment by mkay581** [comment]
No problem. Let's keep in touch. Would love to know what you build! Im at mark[at]heyimmark.com

**Comment by alidcastano** [comment]
hey mark, thanks again for the npm name

my email is alidcastano[at]gmail.com, though I prefer communicating via twitter (@alidcastano) if you have one

also, part of project code/readme is up if you want to check it out and pay homage to the name haha
