### ISSUE TITLE
Error: ENOENT: no such file or directory, stat '/Applications/MAMP/htdocs/TEST/roguetest/public'  at Object.fs.statSync (fs.js:948:11)

### ISSUE THREAD

**Issue by nyl-auster** [alidcastano/rogue#12]
> > roguetest@1.0.0 dev /Applications/MAMP/htdocs/TEST/roguetest
> > rogue dev
> 
> fs.js:948
>   binding.stat(pathModule._makeLong(path));
>           ^
> 
> Error: ENOENT: no such file or directory, stat '/Applications/MAMP/htdocs/TEST/roguetest/public'
>     at Object.fs.statSync (fs.js:948:11)
>     at /Applications/MAMP/htdocs/TEST/roguetest/node_modules/graceful-fs/polyfills.js:297:22
>     at getStats (/Applications/MAMP/htdocs/TEST/roguetest/node_modules/fs-extra/lib/copy-sync/copy-sync.js:42:14)
>     at startCopy (/Applications/MAMP/htdocs/TEST/roguetest/node_modules/fs-extra/lib/copy-sync/copy-sync.js:37:10)
>     at copySync (/Applications/MAMP/htdocs/TEST/roguetest/node_modules/fs-extra/lib/copy-sync/copy-sync.js:32:10)
>     at prepBuild (/Applications/MAMP/htdocs/TEST/roguetest/node_modules/rogue/src/bundler/index.js:55:3)
>     at bundler (/Applications/MAMP/htdocs/TEST/roguetest/node_modules/rogue/src/bundler/index.js:61:3)
>     at Object.<anonymous> (/Applications/MAMP/htdocs/TEST/roguetest/node_modules/rogue/scripts/dev.js:21:23)
>     at Module._compile (module.js:635:30)
>     at Object.Module._extensions..js (module.js:646:10)

**Comment by alidcastano** [comment]
yea just ran into this too

we try to copy your `public` dir over similar to `create-react-app`

Just gonna make sure we check for it before copying it over, one sec

**Comment by alidcastano** [comment]
Ok `rogue@0.1.5` fixes this and another problem I ran into 

I was able to get a `hello-world` running

Closing this!

**Comment by alidcastano** [comment]
Also, @nyl-auster be mindful of #11

**Comment by nyl-auster** [comment]
@alidcastano okay ! yep this is running now \o/

**Comment by alidcastano** [comment]
I have a `with-everything` example coming next
